import trading from "@/ui/icons/trading.svg";
import copy_trading from "@/ui/icons/copy_trading.svg";
import cross_chain from "@/ui/icons/cross_chain.svg";

export const productsType = [
  { name: "Automatic Trading", link: "/automatictrading", icon: trading, description: "Automated trading system" },
  { name: "Copy Trading", link: "/copytrading", icon: copy_trading, description: "LongTerm strategies from Emvios" },
  { name: "CrossChain DEX Trading", link: "/crosschain-dex", icon: cross_chain, description: "Coming soon" },
];

export interface goodsType {
  logo: string;
  name: string;
  description: string;
  profit: number;
  maxDrawdown: number;
  currencyLogo: string;
  currencyName: string;
  exchangeLogo: string;
  exchangeName: string;

}

export const goods = [
  {
    logo: "/bots/BinanceMemeCoinScalper.png",
    name: "Binance MemeCoin Scalper",
    description: "bot-1",
    profit: 1122.24,
    maxDrawdown: 215.21,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/binance.png",
    exchangeName: "Binance",
  },
  {
    logo: "/bots/CryptocomScalpMasterBot.png",
    name: "Crypto.com ScalpMaster Bot",
    description: "bot-2",
    profit: 832.24,
    maxDrawdown: 63.16,
    currencyLogo: "/currency/ethereum.png",
    currencyName: "Ethereum",
    exchangeLogo: "/exchange/crypto.com.png",
    exchangeName: "Crypto.com",
  },
  {
    logo: "/bots/OKXLowRiskIndexCopyBot.png",
    name: "OKX Low-Risk Index Copy Bot",
    description: "bot-3",
    profit: 242.24,
    maxDrawdown: 17.21,
    currencyLogo: "/currency/bnb.png",
    currencyName: "BNB",
    exchangeLogo: "/exchange/okx.png",
    exchangeName: "OKX",
  },
  {
    logo: "/bots/BinanceBNBBollingerBandsBot.png",
    name: "Binance BNB Bollinger Bands Bot",
    description: "bot-4",
    profit: 335.14,
    maxDrawdown: 41.65,
    currencyLogo: "/currency/bnb.png",
    currencyName: "Binance Coin",
    exchangeLogo: "/exchange/binance.png",
    exchangeName: "Binance",
  },
  {
    logo: "/bots/OKXMemeCoinSpeculator.png",
    name: "OKX MemeCoin Speculator",
    description: "bot-5",
    profit: 142.24,
    maxDrawdown: 4.77,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/okx.png",
    exchangeName: "OKX",
  },
  {
    logo: "/bots/HuobiMovingAverageCrossBot.png",
    name: "Huobi Moving Average Cross Bot",
    description: "bot-6",
    profit: 542.15,
    maxDrawdown: 53.52,
    currencyLogo: "/currency/ethereum.png",
    currencyName: "Ethereum",
    exchangeLogo: "/exchange/huobi.png",
    exchangeName: "Huobi",
  },
  {
    logo: "/bots/PoloniexFuturesx5CopyBot.png",
    name: "Poloniex Futures x5 Copy Bot",
    description: "bot-7",
    profit: 182.72,
    maxDrawdown: 24.98,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/poloniex.png",
    exchangeName: "Poloniex",
  },
  {
    logo: "/bots/KuCoinICOScoutBot.png",
    name: "KuCoin ICO Scout Bot",
    description: "bot-8",
    profit: 245.69,
    maxDrawdown: 36.19,
    currencyLogo: "/currency/bitcoin.png",
    currencyName: "Bitcoin",
    exchangeLogo: "/exchange/kucoin.png",
    exchangeName: "KuCoin",
  },
  {
    logo: "/bots/BinanceAltcoinScalperBot.png",
    name: "Binance Altcoin Scalper Bot",
    description: "bot-9",
    profit: 543.12,
    maxDrawdown: 99.95,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/binance.png",
    exchangeName: "Binance",
  },
  {
    logo: "/bots/CoinbaseSectorRotatorBot.png",
    name: "Coinbase Sector Rotator Bot",
    description: "bot-10",
    profit: 76.44,
    maxDrawdown: 13.93,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/coinbase.png",
    exchangeName: "Coinbase",
  },
  {
    logo: "/bots/BinanceETHFuturesTradebot.png",
    name: "Binance ETH Futures Tradebot",
    description: "bot-11",
    profit: 716.74,
    maxDrawdown: 156.19,
    currencyLogo: "/currency/ethereum.png",
    currencyName: "Ethereum",
    exchangeLogo: "/exchange/binance.png",
    exchangeName: "Binance",
  },
  {
    logo: "/bots/OKXGridTradingBot.png",
    name: "OKX Grid Trading Bot",
    description: "bot-12",
    profit: 110.52,
    maxDrawdown: 6.18,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/okx.png",
    exchangeName: "OKX",
  },
  {
    logo: "/bots/KrakenVolumeSpikeBot.png",
    name: "Kraken Volume Spike Bot",
    description: "bot-13",
    profit: 427.55,
    maxDrawdown: 72.29,
    currencyLogo: "/currency/bitcoin.png",
    currencyName: "Bitcoin",
    exchangeLogo: "/exchange/kraken.png",
    exchangeName: "Kraken",
  },
  {
    logo: "/bots/KrakenRebalancingPortfolioBot.png",
    name: "Kraken Rebalancing Portfolio Bot",
    description: "bot-14",
    profit: 66.24,
    maxDrawdown: 3.6,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/kraken.png",
    exchangeName: "Kraken",
  },
  {
    logo: "/bots/BybitFundingRateTrader.png",
    name: "Bybit Funding Rate Trader",
    description: "bot-15",
    profit: 73.24,
    maxDrawdown: 19.51,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/bybit.png",
    exchangeName: "Bybit",
  },
  {
    logo: "/bots/KrakenBreakoutTraderBot.png",
    name: "Kraken Breakout Trader Bot",
    description: "bot-16",
    profit: 159.41,
    maxDrawdown: 17.73,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/kraken.png",
    exchangeName: "Kraken",
  },
  {
    logo: "/bots/BybitDeltaNeutralBot.png",
    name: "Bybit Delta Neutral Bot",
    description: "bot-17",
    profit: 203.11,
    maxDrawdown: 38.29,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/bybit.png",
    exchangeName: "Bybit",
  },
  {
    logo: "/bots/KuCoinVolatilityHunter.png",
    name: "KuCoin Volatility Hunter",
    description: "bot-18",
    profit: 77.48,
    maxDrawdown: 15.11,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/kucoin.png",
    exchangeName: "KuCoin",
  },
  {
    logo: "/bots/CoinbaseProArbitrageExplorer.png",
    name: "Coinbase Pro Arbitrage Explorer",
    description: "bot-19",
    profit: 312.48,
    maxDrawdown: 46.28,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/coinbase.png",
    exchangeName: "Coinbase",
  },
  {
    logo: "/bots/OKXMomentumSwingBot.png",
    name: "OKX Momentum Swing Bot",
    description: "bot-20",
    profit: 477.56,
    maxDrawdown: 99.55,
    currencyLogo: "/currency/bitcoin.png",
    currencyName: "Bitcoin",
    exchangeLogo: "/exchange/okx.png",
    exchangeName: "OKX",
  },
  {
    logo: "/bots/KuCoinFlashArbitrageBot.png",
    name: "KuCoin Flash Arbitrage Bot",
    description: "bot-21",
    profit: 45.25,
    maxDrawdown: 6.12,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/kucoin.png",
    exchangeName: "KuCoin",
  },
  {
    logo: "/bots/PoloniexDCAStrategyBot.png",
    name: "Poloniex DCA Strategy Bot",
    description: "bot-22",
    profit: 152.73,
    maxDrawdown: 8.66,
    currencyLogo: "/currency/bitcoin.png",
    currencyName: "Bitcoin",
    exchangeLogo: "/exchange/poloniex.png",
    exchangeName: "Poloniex",
  },
  {
    logo: "/bots/HuobiHighYieldStakingBot.png",
    name: "Huobi High-Yield Staking Bot",
    description: "bot-23",
    profit: 521.95,
    maxDrawdown: 56.53,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/huobi.png",
    exchangeName: "Huobi",
  },
  {
    logo: "/bots/HuobiSentimentAnalysisBot.png",
    name: "Huobi Sentiment Analysis Bot",
    description: "bot-24",
    profit: 331.19,
    maxDrawdown: 31.19,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/huobi.png",
    exchangeName: "Huobi",
  },
  {
    logo: "/bots/HuobiMeanReversionBot.png",
    name: "Huobi Mean Reversion Bot",
    description: "bot-25",
    profit: 551.87,
    maxDrawdown: 21.73,
    currencyLogo: "/currency/ethereum.png",
    currencyName: "Ethereum",
    exchangeLogo: "/exchange/huobi.png",
    exchangeName: "Huobi",
  },
  {
    logo: "/bots/BitfinexDeFiYieldFarmer.png",
    name: "Bitfinex DeFi Yield Farmer",
    description: "bot-26",
    profit: 32.11,
    maxDrawdown: 24.17,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/bitfinex.png",
    exchangeName: "Bitfinex",
  },
  {
    logo: "/bots/BitfinexCrossExchangeArbitrageBot.png",
    name: "Bitfinex Cross-Exchange Arbitrage Bot",
    description: "bot-27",
    profit: 246.64,
    maxDrawdown: 29.49,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/bitfinex.png",
    exchangeName: "Bitfinex",
  },
  {
    logo: "/bots/BitfinexLeveragex10FuturesBot.png",
    name: "Bitfinex Leverage x10 Futures Bot",
    description: "bot-28",
    profit: 179.88,
    maxDrawdown: 14.88,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/bitfinex.png",
    exchangeName: "Bitfinex",
  },
  {
    logo: "/bots/BinanceFuturesArbitrageBot.png",
    name: "Binance Futures Arbitrage Bot",
    description: "bot-29",
    profit: 228.0,
    maxDrawdown: 17.64,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/binance.png",
    exchangeName: "Binance",
  },
  {
    logo: "/bots/CryptocomLiquidityProviderBot.png",
    name: "Crypto.com Liquidity Provider Bot",
    description: "bot-30",
    profit: 365.11,
    maxDrawdown: 55.11,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/crypto.com.png",
    exchangeName: "Crypto.com",
  },
  {
    logo: "/bots/CryptocomNewsReactiveBot.png",
    name: "Crypto.com News Reactive Bot",
    description: "bot-31",
    profit: 889.64,
    maxDrawdown: 163.18,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/crypto.com.png",
    exchangeName: "Crypto.com",
  },

  {
    logo: "/bots/BybitHighFrequencyArbitrageBot.png",
    name: "Bybit High-Frequency Arbitrage Bot",
    description: "bot-32",
    profit: 472.68,
    maxDrawdown: 69.31,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/bybit.png",
    exchangeName: "Bybit",
  },
  {
    logo: "/bots/BybitMarketMakerBot.png",
    name: "Bybit Market Maker Bot",
    description: "bot-33",
    profit: 110.69,
    maxDrawdown: 42.84,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/bybit.png",
    exchangeName: "Bybit",
  },
  {
    logo: "/bots/PoloniexRSIDivergenceBot.png",
    name: "Poloniex RSI Divergence Bot",
    description: "bot-34",
    profit: 42.68,
    maxDrawdown: 19.51,
    currencyLogo: "/currency/usdc.png",
    currencyName: "USDC",
    exchangeLogo: "/exchange/poloniex.png",
    exchangeName: "Poloniex",
  },
  {
    logo: "/bots/kucoin-delta.png",
    name: "Kucoin Delta Neutral Bot",
    description: "bot-35",
    profit: 567.99,
    maxDrawdown: 67.81,
    currencyLogo: "/currency/ethereum.png",
    currencyName: "Ethereum",
    exchangeLogo: "/exchange/kucoin.png",
    exchangeName: "KuCoin",
  },
  {
    logo: "/bots/PoloniexSmartBetaIndexBot.png",
    name: "Poloniex Smart Beta Index Bot",
    description: "bot-36",
    profit: 324.71,
    maxDrawdown: 42.11,
    currencyLogo: "/currency/tether.png",
    currencyName: "Tether",
    exchangeLogo: "/exchange/poloniex.png",
    exchangeName: "Poloniex",
  },
  ,
] as goodsType[];
